# -*- coding: utf-8 -*-
"""jarak antar planet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HIeHtjpC0d9_oHJJVBEjKRi6d0TXPbVi
"""

import streamlit as st
import matplotlib.pyplot as plt
import numpy as np

# Data Planet (Jarak rata-rata dalam juta km)
planets = {
    'Merkurius': 57.9,
    'Venus': 108.2,
    'Bumi': 149.6,
    'Mars': 227.9,
    'Jupiter': 778.3,
    'Saturnus': 1427.0,
    'Uranus': 2871.0,
    'Neptunus': 4497.1
}

# Fungsi untuk menggambar orbit planet
def plot_orbits():
    fig, ax = plt.subplots(figsize=(8, 6))

    # Set titik pusat (Matahari) di pusat grafik
    ax.plot(0, 0, 'yo', markersize=12, label='Matahari')  # Matahari

    # Gambar orbit planet
    for i, (planet, distance) in enumerate(planets.items()):
        # Set orbit planet (garis melingkar)
        theta = np.linspace(0, 2 * np.pi, 100)
        x = distance * np.cos(theta)
        y = distance * np.sin(theta)
        ax.plot(x, y, label=f'Orbit {planet}')

        # Posisi planet di orbit (mengambil posisi pertama dalam orbit)
        ax.plot(x[0], y[0], 'o', label=planet)

    ax.set_title("Orbit Planet dalam Tata Surya", fontsize=14)
    ax.set_xlabel("Jarak (juta km)")
    ax.set_ylabel("Jarak (juta km)")
    ax.set_aspect('equal', 'box')
    ax.legend(loc="upper right")

    # Menampilkan grid
    ax.grid(True)

    return fig

# Fungsi untuk menghitung jarak antar planet
def calculate_distance(planet1, planet2):
    dist1 = planets[planet1]  # Jarak planet pertama
    dist2 = planets[planet2]  # Jarak planet kedua
    return abs(dist1 - dist2)  # Menghitung selisih jarak

# Streamlit interface
st.title("Virtual Lab: Pengukuran Jarak Antar Planet")
st.sidebar.header("Pilih Dua Planet")

planet_choices = list(planets.keys())
planet1 = st.sidebar.selectbox("Pilih Planet 1", planet_choices)
planet2 = st.sidebar.selectbox("Pilih Planet 2", planet_choices)

# Tampilkan jarak antar planet yang dipilih
if planet1 and planet2:
    distance = calculate_distance(planet1, planet2)
    st.write(f"Jarak antara {planet1} dan {planet2} adalah {distance:.2f} juta km")

# Tampilkan Orbit Planet
st.subheader("Orbit Planet-planet")
fig = plot_orbits()
st.pyplot(fig)