# -*- coding: utf-8 -*-
"""jarak antar planet revisi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HIeHtjpC0d9_oHJJVBEjKRi6d0TXPbVi
"""

import streamlit as st

# Data planet (jarak rata-rata dalam juta km)
planets = {
    'Merkurius': 57.9,
    'Venus': 108.2,
    'Bumi': 149.6,
    'Mars': 227.9,
    'Jupiter': 778.3,
    'Saturnus': 1427.0,
    'Uranus': 2871.0,
    'Neptunus': 4497.1
}

# Fungsi untuk menghitung jarak antar planet
def calculate_distance(planet1, planet2):
    dist1 = planets[planet1]  # Jarak planet pertama
    dist2 = planets[planet2]  # Jarak planet kedua
    return abs(dist1 - dist2)  # Menghitung selisih jarak

# Streamlit interface
st.title("Virtual Lab: Pengukuran Jarak Antar Planet")
st.sidebar.header("Pilih Dua Planet")

planet_choices = list(planets.keys())
planet1 = st.sidebar.selectbox("Pilih Planet 1", planet_choices)
planet2 = st.sidebar.selectbox("Pilih Planet 2", planet_choices)

# Tampilkan jarak antar planet yang dipilih
if planet1 and planet2:
    distance = calculate_distance(planet1, planet2)
    st.write(f"Jarak antara {planet1} dan {planet2} adalah {distance:.2f} juta km")

# Tampilkan informasi planet dan jaraknya
st.subheader("Jarak Planet dari Matahari (dalam juta km):")
for planet, distance in planets.items():
    st.write(f"{planet}: {distance} juta km")

# Menambahkan visualisasi orbit planet menggunakan teks sederhana
st.subheader("Visualisasi Orbit Planet (Simbol Sederhana)")

# Membuat orbit planet sederhana dalam bentuk teks
for planet, distance in planets.items():
    orbit = ' ' * int(distance / 10) + "o"  # Tanda 'o' mewakili posisi planet
    st.write(f"Orbit {planet}: {'-' * int(distance / 10)} {orbit}")