# -*- coding: utf-8 -*-
"""jarak antar planett.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HIeHtjpC0d9_oHJJVBEjKRi6d0TXPbVi
"""

import streamlit as st
import numpy as np

# --- Data Planet (Jarak rata-rata dari Matahari dalam AU) ---
# Anda bisa menambahkan lebih banyak planet di sini
planet_data = {
    "Merkurius": 0.39,
    "Venus": 0.72,
    "Bumi": 1.00,
    "Mars": 1.52,
    "Jupiter": 5.20,
    "Saturnus": 9.58,
    "Uranus": 19.22,
    "Neptunus": 30.05
}

# --- Fungsi untuk Menghitung Jarak ---
def calculate_distance(planet1_distance, planet2_distance, angle_degrees):
    """
    Menghitung jarak antara dua planet menggunakan Hukum Kosinus.
    Asumsi: Sudut diberikan dalam derajat.
    """
    angle_radians = np.radians(angle_degrees)
    distance = np.sqrt(
        planet1_distance**2 + planet2_distance**2 -
        2 * planet1_distance * planet2_distance * np.cos(angle_radians)
    )
    return distance

# --- Tampilan Aplikasi Streamlit ---
def main():
    st.title("Kalkulator Jarak Antar Planet Sederhana")
    st.write("Hitung perkiraan jarak antar dua planet di Tata Surya.")

    # Pilihan Planet
    planet1 = st.selectbox("Pilih Planet Pertama:", list(planet_data.keys()))
    planet2 = st.selectbox("Pilih Planet Kedua:", list(planet_data.keys()))

    # Input Sudut (Simulasi Posisi Relatif)
    st.write("### Posisi Relatif Planet")
    st.info("Asumsikan Anda mengetahui sudut relatif antara kedua planet terhadap Matahari. "
            "Untuk perhitungan sederhana, anggap kedua planet dan Matahari membentuk segitiga.")

    angle = st.slider("Sudut antara Planet 1, Matahari, dan Planet 2 (derajat):", 0, 180, 90)

    # Tombol Hitung
    if st.button("Hitung Jarak"):
        if planet1 == planet2:
            st.warning("Tidak bisa menghitung jarak antara planet yang sama. Pilih planet yang berbeda.")
        else:
            dist1 = planet_data[planet1]
            dist2 = planet_data[planet2]

            # Hitung jarak
            calculated_dist = calculate_distance(dist1, dist2, angle)

            st.success(f"Jarak antara **{planet1}** dan **{planet2}** adalah sekitar **{calculated_dist:.2f} AU**.")
            st.info("Catatan: Ini adalah perhitungan yang disederhanakan dan tidak memperhitungkan orbit elips, inklinasi, atau posisi real-time.")

if __name__ == "__main__":
    main()